package com.cbs.treasury.entity;

public enum DealType {
    FX_SPOT, FX_FORWARD, FX_SWAP, MONEY_MARKET_PLACEMENT,
    MONEY_MARKET_BORROWING, BOND_PURCHASE, BOND_SALE,
    REPO, REVERSE_REPO, TBILL_PURCHASE, TBILL_DISCOUNT
}
