module.exports = {
  apps: [
    {
      name: 'cbs-backend',
      script: 'java',
      args: '-jar build/libs/cbs-1.0.0-SNAPSHOT.jar',
      cwd: '/Users/mac/codes/cba',
      interpreter: 'none',
      env: {
        CBS_DB_URL: 'jdbc:postgresql://localhost:5432/cbs',
        CBS_DB_USERNAME: 'cbs_admin',
        CBS_DB_PASSWORD: 'cbs_password',
        CBS_REDIS_HOST: 'localhost',
        CBS_REDIS_PORT: '6379',
        CBS_SERVER_PORT: '8080',
        CBS_CACHE_TYPE: 'redis',
        CBS_OAUTH2_ISSUER_URI: 'http://localhost:8180/realms/cbs',
        CBS_OAUTH2_ACCEPTED_AUDIENCES: 'cbs-app',
        SPRING_PROFILES_ACTIVE: 'dev',
        JAVA_OPTS: '-Xmx512m -Xms256m',
      },
      watch: false,
      autorestart: true,
      max_restarts: 3,
      restart_delay: 5000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      out_file: '/Users/mac/codes/cba/logs/backend.out.log',
      error_file: '/Users/mac/codes/cba/logs/backend.err.log',
      merge_logs: true,
    },
    {
      name: 'cbs-frontend',
      script: 'npm',
      args: 'run dev',
      cwd: '/Users/mac/codes/cba/cbs-frontend',
      interpreter: 'none',
      env: {
        NODE_ENV: 'development',
      },
      watch: false,
      autorestart: true,
      max_restarts: 5,
      restart_delay: 3000,
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      out_file: '/Users/mac/codes/cba/logs/frontend.out.log',
      error_file: '/Users/mac/codes/cba/logs/frontend.err.log',
      merge_logs: true,
    },
  ],
};
