let seq = 0;

export function createMockCard(overrides: Record<string, unknown> = {}) {
  seq++;
  return {
    id: seq,
    cardReference: `CRD-${String(seq).padStart(6, '0')}`,
    cardNumberMasked: `**** **** **** ${String(1000 + seq)}`,
    accountId: seq,
    accountNumber: `01${String(seq).padStart(8, '0')}`,
    customerId: seq,
    customerDisplayName: `Card Holder ${seq}`,
    cardType: 'DEBIT',
    cardScheme: 'VISA',
    cardTier: 'CLASSIC',
    cardholderName: `CARD HOLDER ${seq}`,
    issueDate: '2024-03-15',
    expiryDate: '2028-03-15',
    lastUsedDate: null,
    dailyPosLimit: 500000,
    dailyAtmLimit: 200000,
    dailyOnlineLimit: 300000,
    singleTxnLimit: 200000,
    monthlyLimit: 5000000,
    creditLimit: null,
    availableCredit: null,
    outstandingBalance: null,
    contactlessEnabled: true,
    onlineEnabled: true,
    internationalEnabled: false,
    atmEnabled: true,
    posEnabled: true,
    pinRetriesRemaining: 3,
    status: 'ACTIVE',
    blockReason: null,
    currencyCode: 'NGN',
    branchCode: 'LG001',
    deliveryMethod: 'BRANCH_PICKUP',
    createdAt: '2024-03-15T10:00:00Z',
    updatedAt: '2024-03-15T10:00:00Z',
    ...overrides,
  };
}

export function createMockCardTransaction(overrides: Record<string, unknown> = {}) {
  seq++;
  return {
    id: seq,
    transactionRef: `TXN-${String(seq).padStart(8, '0')}`,
    cardId: 1,
    cardReference: 'CRD-000001',
    accountId: 1,
    accountNumber: '0100000001',
    transactionType: 'PURCHASE',
    channel: 'POS',
    amount: 15000,
    currencyCode: 'NGN',
    billingAmount: 15000,
    billingCurrency: 'NGN',
    fxRate: null,
    merchantName: `Merchant ${seq}`,
    merchantId: `M-${seq}`,
    merchantCategoryCode: '5411',
    terminalId: `T-${seq}`,
    merchantCity: 'Lagos',
    merchantCountry: 'NGA',
    international: false,
    authCode: `A${String(seq).padStart(5, '0')}`,
    responseCode: '00',
    status: 'AUTHORIZED',
    declineReason: null,
    disputed: false,
    disputeReason: null,
    disputeDate: null,
    transactionDate: '2026-01-15T14:30:00Z',
    settlementDate: null,
    ...overrides,
  };
}
