// Auto-generated from backend entities

export interface PriceQuote {
  id: number;
  quoteRef: string;
  deskId: number;
  dealerId: string;
  quoteType: string;
  instrumentType: string;
  instrumentCode: string;
  currencyPair: string;
  tenor: string;
  bidPrice: number;
  askPrice: number;
  midPrice: number;
  spreadBps: number;
  notionalAmount: number;
  currency: string;
  counterpartyCode: string;
  counterpartyName: string;
  validFromTime: string;
  validUntilTime: string;
  isAutoGenerated: boolean;
  pricingModel: string;
  marketDataRef: string;
  status: string;
  tradedRef: string;
}

export interface QuoteRequest {
  id: number;
  requestRef: string;
  requestorType: string;
  requestorId: string;
  requestorName: string;
  instrumentType: string;
  currencyPair: string;
  tenor: string;
  amount: number;
  direction: string;
  requestedAt: string;
  responseDeadline: string;
  assignedDeskId: number;
  assignedDealerId: string;
  quotesProvided: number;
  selectedQuoteId: number;
  status: string;
}

