import { apiGet, apiPost } from '@/lib/api';
import api from '@/lib/api';
import type { Counterparty } from '../types/counterparty';

export const counterpartiesApi = {
  /** GET /v1/counterparties */
  getAll: () => apiGet<Counterparty[]>('/api/v1/counterparties'),

  /** GET /v1/counterparties/{code} */
  getByCode: (code: string) => apiGet<Counterparty>(`/api/v1/counterparties/${code}`),

  /** POST /v1/counterparties (CBS_ADMIN only) — code is auto-generated by backend */
  create: (data: {
    counterpartyName: string;
    counterpartyType: string;
    lei?: string;
    bicCode?: string;
    country: string;
    creditRating?: string;
    ratingAgency?: string;
    totalExposureLimit: number;
    riskCategory: string;
    nettingAgreement?: boolean;
    isdaAgreement?: boolean;
    csaAgreement?: boolean;
  }) => apiPost<Counterparty>('/api/v1/counterparties', data),

  // Backend: PATCH /{code}/exposure?exposure=... (CBS_ADMIN only, @RequestParam BigDecimal exposure)
  updateExposure: (code: string, exposure: number) => {
    const params = new URLSearchParams({ exposure: String(exposure) });
    return api.patch<{ data: Counterparty }>(
      `/api/v1/counterparties/${code}/exposure?${params}`,
    ).then((r) => r.data.data);
  },

  // Backend: POST /{code}/verify-kyc — no body, CBS_ADMIN only
  verifyKyc: (code: string) =>
    apiPost<Counterparty>(`/api/v1/counterparties/${code}/verify-kyc`),

  /** GET /v1/counterparties/type/{type} */
  byType: (type: string) =>
    apiGet<Counterparty[]>(`/api/v1/counterparties/type/${type}`),

  /** GET /v1/counterparties/pending-kyc (CBS_ADMIN only) */
  pendingKyc: () =>
    apiGet<Counterparty[]>('/api/v1/counterparties/pending-kyc'),
};
