package com.cbs.trade.entity;

public enum TradeDocCategory {
    INVOICE, BILL_OF_LADING, PACKING_LIST, CERTIFICATE_OF_ORIGIN,
    INSURANCE_CERT, INSPECTION_CERT, WEIGHT_CERT, PHYTOSANITARY,
    CUSTOMS_DECLARATION, DRAFT, OTHER
}
