package com.cbs.fees.entity;

public enum FeeCategory {
    ACCOUNT_MAINTENANCE, TRANSACTION, CARD, LOAN_PROCESSING,
    STATEMENT, CHEQUE, SWIFT, ATM, POS, ONLINE,
    PENALTY, COMMISSION, SERVICE_CHARGE, OTHER
}
