package com.cbs.card.dispute;

public enum DisputeStatus {
    INITIATED, INVESTIGATION, CHARGEBACK_FILED,
    REPRESENTMENT, PRE_ARBITRATION, ARBITRATION,
    RESOLVED_CUSTOMER, RESOLVED_MERCHANT, WITHDRAWN, EXPIRED
}
