package com.cbs.card.dispute;

public enum DisputeType {
    FRAUD, MERCHANDISE_NOT_RECEIVED, DEFECTIVE_MERCHANDISE,
    DUPLICATE_CHARGE, INCORRECT_AMOUNT, CANCELLED_RECURRING,
    NOT_RECOGNISED, SERVICE_NOT_PROVIDED, ATM_DISPUTE, OTHER
}
