package com.cbs.payments.entity;

public enum PaymentType {
    INTERNAL_TRANSFER, DOMESTIC_INSTANT, DOMESTIC_BATCH,
    INTERNATIONAL_WIRE, DIRECT_DEBIT, STANDING_ORDER,
    BILL_PAYMENT, QR_PAYMENT, MOBILE_MONEY
}
