package com.cbs.lending.entity;

public enum LoanType {
    TERM_LOAN, REVOLVING, OVERDRAFT, MORTGAGE, VEHICLE,
    PERSONAL, EDUCATION, AGRICULTURE, TRADE_FINANCE,
    MURABAHA, IJARA, MUSHARAKA, MUDARABA, ISTISNA, SALAM
}
