package com.cbs.lending.entity;

public enum LoanApplicationStatus {
    DRAFT, SUBMITTED, UNDER_REVIEW, CREDIT_CHECK,
    APPROVED, CONDITIONALLY_APPROVED, DECLINED, WITHDRAWN,
    OFFER_ISSUED, OFFER_ACCEPTED, DISBURSED, CANCELLED
}
