/**
 * Consolidated market data types.
 *
 * All domain types for the market-data feature live here.
 * API and hook files should import from this barrel.
 */

// ─── Re-exports from auto-generated entity files ─────────────────────────────

export type { MarketAnalysisReport } from './marketAnalysis';
export type { MarketDataFeed, MarketPrice as MarketPriceExt, MarketSignal as MarketSignalExt } from './marketDataExt';
export type { MarketDataSubscription } from './marketDataSwitch';
export type { MarketMakingActivity, MarketMakingMandate } from './marketMaking';
export type { MarketResearchProject as MarketResearchProjectExt } from './marketResearch';

// ─── Enums & Literal Types ───────────────────────────────────────────────────

/** Status of a market data feed connection. */
export type FeedStatus = 'ACTIVE' | 'STALE' | 'DOWN';

/** Whether a feed delivers real-time or end-of-day data. */
export type FeedType = 'REALTIME' | 'EOD';

/** Trading signal direction. */
export type SignalType = 'BUY' | 'SELL' | 'HOLD';

/** Analyst recommendation on an instrument. */
export type Recommendation = 'BUY' | 'HOLD' | 'SELL';

/** Category of market analysis. */
export type AnalysisType = 'TECHNICAL' | 'FUNDAMENTAL' | 'SECTOR' | 'MACRO';

/** Type of market research project. */
export type ResearchProjectType =
  | 'CUSTOMER_SURVEY'
  | 'COMPETITIVE_ANALYSIS'
  | 'PRODUCT_STUDY'
  | 'MARKET_SIZING';

// ─── Domain Interfaces ───────────────────────────────────────────────────────

/** A registered market data feed and its current health. */
export interface DataFeed {
  feedId: string;
  provider: string;
  assetClass: string;
  feedType: FeedType;
  instruments: string[];
  lastReceivedAt: string;
  latencyMs?: number;
  status: FeedStatus;
  createdAt?: string;
}

/** Quality metrics for a single data feed. */
export interface FeedQualityMetric {
  feedId: string;
  provider: string;
  assetClass: string;
  completeness: number;
  accuracy: number;
  timeliness: number;
  errorCount: number;
  overallScore: number;
}

/** Real-time / latest price for a financial instrument. */
export interface MarketPrice {
  instrumentCode: string;
  instrumentName?: string;
  bid: number;
  ask: number;
  last: number;
  volume: number;
  changePct: number;
  changeAbs?: number;
  currency?: string;
  source?: string;
  recordedAt: string;
}

/** A trading signal generated by analytics or an analyst. */
export interface MarketSignal {
  id: number;
  instrumentCode: string;
  signal: SignalType;
  confidence: number;
  source: string;
  analyst?: string;
  summary?: string;
  generatedAt: string;
}

/** A published research report on a specific instrument. */
export interface ResearchReport {
  id: number;
  title: string;
  instrumentCode: string;
  analyst: string;
  recommendation: Recommendation;
  targetPrice: number;
  summary: string;
  reportUrl?: string;
  publishedAt: string;
}

/** A single market analysis (technical, fundamental, etc.). */
export interface MarketAnalysis {
  id: number;
  code?: string;
  title: string;
  type: AnalysisType;
  instrument?: string;
  sector?: string;
  summary: string;
  status: 'DRAFT' | 'PUBLISHED';
  publishedAt?: string;
  createdAt: string;
}

/** A market research project (survey, sizing, etc.). */
export interface MarketResearchProject {
  id: number;
  code: string;
  title: string;
  type: ResearchProjectType;
  description: string;
  status: 'ACTIVE' | 'COMPLETED';
  findings?: string;
  keyInsights?: string[];
  actionItems?: string[];
  completedAt?: string;
  createdAt: string;
}

/** Aggregate dashboard for the market data switch. */
export interface SwitchDashboard {
  totalFeeds: number;
  activeFeeds: number;
  messagesPerSec: number;
  errorRate: number;
  uptimePct?: number;
  lastUpdated?: string;
}

/** Health report for a single subscription going through the switch. */
export interface SubscriptionHealth {
  subscriptionId: string;
  switchId: string;
  provider: string;
  instrument: string;
  priority: number;
  status: 'HEALTHY' | 'DEGRADED' | 'FAILED';
  latencyMs: number;
  lastHeartbeatAt: string;
}

/** A market data switch instance. */
export interface MarketDataSwitch {
  id: string;
  name: string;
  type: string;
  status: 'RUNNING' | 'STOPPED';
  createdAt: string;
}

/** FX rate for a currency pair, used by the useFxRate hook. */
export interface FxRate {
  bid: number;
  ask: number;
  mid: number;
  spread: number;
  updatedAt: string;
}
