import type { Card, CardTransaction, Merchant, PosTerminal } from '../types/card';

export const mockCards: Card[] = [
  { id: 1, cardNumberMasked: '**** **** **** 1234', customerName: 'Adeola Johnson', customerId: 1, cardType: 'DEBIT', scheme: 'VISA', accountNumber: '0123456789', accountId: 1, expiryDate: '03/28', nameOnCard: 'ADEOLA JOHNSON', status: 'ACTIVE', issuedDate: '2024-03-15', deliveryMethod: 'BRANCH_PICKUP', controls: { posEnabled: true, atmEnabled: true, onlineEnabled: false, internationalEnabled: false, contactlessEnabled: true, recurringEnabled: true } },
  { id: 2, cardNumberMasked: '**** **** **** 5678', customerName: 'Chidi Okafor', customerId: 2, cardType: 'CREDIT', scheme: 'MASTERCARD', accountNumber: '0987654321', accountId: 2, expiryDate: '06/27', nameOnCard: 'CHIDI OKAFOR', status: 'ACTIVE', issuedDate: '2023-06-20', deliveryMethod: 'COURIER', controls: { posEnabled: true, atmEnabled: true, onlineEnabled: true, internationalEnabled: true, contactlessEnabled: true, recurringEnabled: true } },
  { id: 3, cardNumberMasked: '**** **** **** 9012', customerName: 'Fatima Musa', customerId: 3, cardType: 'DEBIT', scheme: 'VERVE', accountNumber: '1122334455', accountId: 3, expiryDate: '12/26', nameOnCard: 'FATIMA MUSA', status: 'BLOCKED', issuedDate: '2022-12-01', deliveryMethod: 'BRANCH_PICKUP', controls: { posEnabled: false, atmEnabled: false, onlineEnabled: false, internationalEnabled: false, contactlessEnabled: false, recurringEnabled: false } },
  { id: 4, cardNumberMasked: '**** **** **** 3456', customerName: 'Emeka Nwosu', customerId: 4, cardType: 'PREPAID', scheme: 'VISA', accountNumber: '5566778899', accountId: 4, expiryDate: '09/27', nameOnCard: 'EMEKA NWOSU', status: 'PENDING_ACTIVATION', issuedDate: '2026-03-10', deliveryMethod: 'COURIER', controls: { posEnabled: true, atmEnabled: true, onlineEnabled: false, internationalEnabled: false, contactlessEnabled: true, recurringEnabled: false } },
  { id: 5, cardNumberMasked: '**** **** **** 7890', customerName: 'Ngozi Eze', customerId: 5, cardType: 'DEBIT', scheme: 'MASTERCARD', accountNumber: '6677889900', accountId: 5, expiryDate: '01/26', nameOnCard: 'NGOZI EZE', status: 'EXPIRED', issuedDate: '2022-01-18', deliveryMethod: 'BRANCH_PICKUP', controls: { posEnabled: false, atmEnabled: false, onlineEnabled: false, internationalEnabled: false, contactlessEnabled: false, recurringEnabled: false } },
];

export const mockCardTransactions: CardTransaction[] = [
  { id: 1, transactionRef: 'CSW-20260318-001', cardMasked: '**** 1234', merchantName: 'Shoprite Victoria Island', merchantId: 'M-001', mcc: '5411', mccDescription: 'Grocery Stores', amount: 25000, currency: 'NGN', authCode: '123456', responseCode: '00', responseDescription: 'Approved', channel: 'POS', transactionDate: new Date(Date.now() - 2 * 3600000).toISOString(), status: 'APPROVED', fraudScore: 12 },
  { id: 2, transactionRef: 'CSW-20260318-002', cardMasked: '**** 5678', merchantName: 'Shell Filling Station Lekki', merchantId: 'M-002', mcc: '5541', mccDescription: 'Service Stations', amount: 50000, currency: 'NGN', authCode: '234567', responseCode: '00', responseDescription: 'Approved', channel: 'POS', transactionDate: new Date(Date.now() - 4 * 3600000).toISOString(), status: 'APPROVED', fraudScore: 8 },
  { id: 3, transactionRef: 'CSW-20260318-003', cardMasked: '**** 1234', merchantName: 'Amazon.com', merchantId: 'M-003', mcc: '5942', mccDescription: 'Book Stores', amount: 15000, currency: 'USD', authCode: '', responseCode: '51', responseDescription: 'Insufficient Funds', channel: 'ONLINE', transactionDate: new Date(Date.now() - 6 * 3600000).toISOString(), status: 'DECLINED', fraudScore: 45 },
  { id: 4, transactionRef: 'CSW-20260318-004', cardMasked: '**** 9012', merchantName: 'ATM - BellBank HQ', merchantId: 'ATM-001', mcc: '6011', mccDescription: 'ATM Cash Disbursement', amount: 100000, currency: 'NGN', authCode: '345678', responseCode: '00', responseDescription: 'Approved', channel: 'ATM', transactionDate: new Date(Date.now() - 8 * 3600000).toISOString(), status: 'APPROVED', fraudScore: 5 },
  { id: 5, transactionRef: 'CSW-20260318-005', cardMasked: '**** 5678', merchantName: 'Jumia Nigeria', merchantId: 'M-004', mcc: '5999', mccDescription: 'Misc Retail', amount: 89000, currency: 'NGN', authCode: '456789', responseCode: '00', responseDescription: 'Approved', channel: 'ONLINE', transactionDate: new Date(Date.now() - 12 * 3600000).toISOString(), status: 'APPROVED', fraudScore: 22 },
  { id: 6, transactionRef: 'CSW-20260318-006', cardMasked: '**** 3456', merchantName: 'Uber Nigeria', merchantId: 'M-005', mcc: '4121', mccDescription: 'Taxicabs/Limousines', amount: 3500, currency: 'NGN', authCode: '', responseCode: '05', responseDescription: 'Do Not Honour', channel: 'ONLINE', transactionDate: new Date(Date.now() - 14 * 3600000).toISOString(), status: 'DECLINED', fraudScore: 78 },
];

export const mockMerchants: Merchant[] = [
  { id: 1, merchantId: 'MCH-001', merchantName: 'Shoprite Nigeria', mcc: '5411', mccDescription: 'Grocery Stores', terminalCount: 145, monthlyVolume: 2500000000, mdrRate: 0.75, chargebackRate: 0.1, riskCategory: 'LOW', status: 'ACTIVE', onboardedDate: '2022-01-15' },
  { id: 2, merchantId: 'MCH-002', merchantName: 'Jumia Nigeria', mcc: '5999', mccDescription: 'Misc Retail', terminalCount: 0, monthlyVolume: 1800000000, mdrRate: 1.5, chargebackRate: 0.8, riskCategory: 'MEDIUM', status: 'ACTIVE', onboardedDate: '2023-03-20' },
  { id: 3, merchantId: 'MCH-003', merchantName: 'Total Energies', mcc: '5541', mccDescription: 'Service Stations', terminalCount: 320, monthlyVolume: 4500000000, mdrRate: 0.5, chargebackRate: 0.05, riskCategory: 'LOW', status: 'ACTIVE', onboardedDate: '2021-06-10' },
  { id: 4, merchantId: 'MCH-004', merchantName: 'Bet9ja', mcc: '7995', mccDescription: 'Betting', terminalCount: 12, monthlyVolume: 890000000, mdrRate: 2.0, chargebackRate: 2.1, riskCategory: 'HIGH', status: 'ACTIVE', onboardedDate: '2024-01-05' },
];

export const mockTerminals: PosTerminal[] = [
  { id: 1, terminalId: 'POS-VIC-001', merchantName: 'Shoprite V.I.', location: 'Victoria Island, Lagos', model: 'PAX A920', lastTransaction: new Date(Date.now() - 5 * 60000).toISOString(), onlineStatus: 'ONLINE', deployedDate: '2025-01-10' },
  { id: 2, terminalId: 'POS-LEK-001', merchantName: 'Total Lekki', location: 'Lekki Phase 1, Lagos', model: 'Ingenico Move 5000', lastTransaction: new Date(Date.now() - 2 * 3600000).toISOString(), onlineStatus: 'IDLE', deployedDate: '2024-08-15' },
  { id: 3, terminalId: 'POS-ABJ-001', merchantName: 'Shoprite Wuse', location: 'Wuse 2, Abuja', model: 'PAX A920', lastTransaction: new Date(Date.now() - 30 * 3600000).toISOString(), onlineStatus: 'OFFLINE', deployedDate: '2024-06-20' },
];
