package com.cbs.aml.entity;

public enum AmlRuleCategory {
    STRUCTURING, VELOCITY, LARGE_CASH, ROUND_AMOUNT,
    HIGH_RISK_COUNTRY, PEP, DORMANT_REACTIVATION,
    UNUSUAL_PATTERN, LAYERING, RAPID_MOVEMENT, CUSTOM
}
