package com.cbs.limits.entity;

public enum LimitType {
    DAILY_DEBIT, DAILY_CREDIT, SINGLE_TRANSACTION,
    DAILY_TRANSFER, MONTHLY_TRANSFER, DAILY_WITHDRAWAL,
    DAILY_POS, DAILY_ONLINE, DAILY_INTERNATIONAL
}
