SET search_path TO cbs;

INSERT INTO chart_of_accounts (
    gl_code,
    gl_name,
    gl_category,
    level_number,
    is_header,
    is_postable,
    is_multi_currency,
    is_inter_branch,
    normal_balance,
    allow_manual_posting,
    requires_cost_centre,
    is_active,
    islamic_account_category,
    contract_type_code,
    shariah_classification,
    is_islamic_account,
    aaoifi_reference,
    aaoifi_line_item,
    profit_distribution_eligible,
    zakat_applicable,
    is_reserve_account,
    reserve_type,
    created_by,
    created_at,
    updated_at,
    version
) VALUES (
    '3100-MDR-001',
    'Unrestricted Investment Accounts - Mudarabah',
    'EQUITY',
    1,
    FALSE,
    TRUE,
    FALSE,
    FALSE,
    'CREDIT',
    TRUE,
    FALSE,
    TRUE,
    'UNRESTRICTED_INVESTMENT_ACCOUNT',
    'MUDARABAH',
    'HALAL',
    TRUE,
    'FAS 1',
    'Unrestricted investment accounts',
    FALSE,
    FALSE,
    FALSE,
    'NONE',
    'SYSTEM',
    NOW(),
    NOW(),
    0
)
ON CONFLICT (gl_code) DO UPDATE SET
    gl_name = EXCLUDED.gl_name,
    gl_category = EXCLUDED.gl_category,
    level_number = EXCLUDED.level_number,
    is_header = EXCLUDED.is_header,
    is_postable = EXCLUDED.is_postable,
    is_multi_currency = EXCLUDED.is_multi_currency,
    is_inter_branch = EXCLUDED.is_inter_branch,
    normal_balance = EXCLUDED.normal_balance,
    allow_manual_posting = EXCLUDED.allow_manual_posting,
    requires_cost_centre = EXCLUDED.requires_cost_centre,
    is_active = EXCLUDED.is_active,
    islamic_account_category = EXCLUDED.islamic_account_category,
    contract_type_code = EXCLUDED.contract_type_code,
    shariah_classification = EXCLUDED.shariah_classification,
    is_islamic_account = EXCLUDED.is_islamic_account,
    aaoifi_reference = EXCLUDED.aaoifi_reference,
    aaoifi_line_item = EXCLUDED.aaoifi_line_item,
    profit_distribution_eligible = EXCLUDED.profit_distribution_eligible,
    zakat_applicable = EXCLUDED.zakat_applicable,
    is_reserve_account = EXCLUDED.is_reserve_account,
    reserve_type = EXCLUDED.reserve_type,
    updated_at = NOW();