SET search_path TO cbs;

-- =====================================================
-- V40: Capital Markets & Suitability (Batch 34)
-- =====================================================

-- 1. Capital Market Deal (ECM/DCM deal tracking)
CREATE TABLE IF NOT EXISTS capital_market_deal (
    id                          BIGSERIAL PRIMARY KEY,
    deal_code                   VARCHAR(30)    NOT NULL UNIQUE,
    deal_type                   VARCHAR(20)    NOT NULL CHECK (deal_type IN ('IPO','FOLLOW_ON','RIGHTS_ISSUE','BOND_ISSUANCE','SUKUK','COMMERCIAL_PAPER','MEDIUM_TERM_NOTE','SECURITIZATION','CONVERTIBLE')),
    market_type                 VARCHAR(5)     NOT NULL CHECK (market_type IN ('ECM','DCM')),
    issuer_name                 VARCHAR(200)   NOT NULL,
    issuer_customer_id          BIGINT,
    issuer_sector               VARCHAR(40),
    currency                    VARCHAR(3)     NOT NULL DEFAULT 'NGN',
    target_amount               NUMERIC(20,4)  NOT NULL,
    actual_amount               NUMERIC(20,4)  DEFAULT 0,
    issue_price                 NUMERIC(20,8),
    coupon_rate                 NUMERIC(8,4),
    tenor_months                INT,
    maturity_date               DATE,
    our_role                    VARCHAR(20)    NOT NULL CHECK (our_role IN ('LEAD_MANAGER','JOINT_LEAD','CO_MANAGER','UNDERWRITER','BOOKRUNNER','FINANCIAL_ADVISER','SELLING_AGENT','RECEIVING_AGENT')),
    our_commitment_amount       NUMERIC(20,4),
    our_fee_pct                 NUMERIC(5,4),
    our_fee_amount              NUMERIC(15,4),
    mandate_date                DATE,
    prospectus_date             DATE,
    book_build_start_date       DATE,
    book_build_end_date         DATE,
    pricing_date                DATE,
    allotment_date              DATE,
    listing_date                DATE,
    settlement_date             DATE,
    regulatory_approval_ref     VARCHAR(80),
    exchange                    VARCHAR(60),
    listing_ref                 VARCHAR(30),
    prospectus_ref              VARCHAR(200),
    credit_rating               VARCHAR(10),
    rating_agency               VARCHAR(60),
    subscription_level          NUMERIC(8,2),
    allocation_method           VARCHAR(15)    CHECK (allocation_method IN ('PRO_RATA','DISCRETIONARY','BALLOT','PRIORITY')),
    syndicate_id                BIGINT,
    status                      VARCHAR(15)    NOT NULL DEFAULT 'MANDATE' CHECK (status IN ('MANDATE','STRUCTURING','REGULATORY_REVIEW','BOOK_BUILDING','PRICED','ALLOTTED','SETTLED','LISTED','CANCELLED')),
    created_by                  VARCHAR(100),
    updated_by                  VARCHAR(100),
    created_at                  TIMESTAMP      NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMP      NOT NULL DEFAULT now(),
    version                     BIGINT         DEFAULT 0
);

CREATE INDEX idx_cmdeal_status ON capital_market_deal(status, market_type);

-- 2. Deal Investor (subscriptions/bids for capital market deals)
CREATE TABLE IF NOT EXISTS deal_investor (
    id                          BIGSERIAL PRIMARY KEY,
    deal_id                     BIGINT         NOT NULL REFERENCES capital_market_deal(id),
    investor_name               VARCHAR(200)   NOT NULL,
    investor_type               VARCHAR(20)    NOT NULL CHECK (investor_type IN ('INSTITUTIONAL','RETAIL','HNI','PENSION_FUND','INSURANCE','MUTUAL_FUND','SOVEREIGN_WEALTH','CORPORATE','STAFF','GOVERNMENT')),
    bid_amount                  NUMERIC(20,4)  NOT NULL,
    bid_price                   NUMERIC(20,8),
    allotted_amount             NUMERIC(20,4),
    allotted_units              NUMERIC(20,6),
    payment_received            NUMERIC(20,4)  DEFAULT 0,
    refund_amount               NUMERIC(20,4)  DEFAULT 0,
    certificate_ref             VARCHAR(80),
    status                      VARCHAR(15)    NOT NULL DEFAULT 'BID_RECEIVED' CHECK (status IN ('BID_RECEIVED','ALLOTTED','PAID','REFUNDED','CANCELLED')),
    created_by                  VARCHAR(100),
    updated_by                  VARCHAR(100),
    created_at                  TIMESTAMP      NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMP      NOT NULL DEFAULT now(),
    version                     BIGINT         DEFAULT 0
);

-- 3. Public Offering Detail (IPO/public offering specifics)
CREATE TABLE IF NOT EXISTS public_offering_detail (
    id                          BIGSERIAL PRIMARY KEY,
    deal_id                     BIGINT         NOT NULL REFERENCES capital_market_deal(id),
    offering_type               VARCHAR(15)    NOT NULL CHECK (offering_type IN ('IPO','SECONDARY','RIGHTS_ISSUE','FOLLOW_ON','OFFER_FOR_SALE','OFFER_FOR_SUBSCRIPTION')),
    exchange_market             VARCHAR(60)    NOT NULL,
    shares_offered              BIGINT         NOT NULL,
    par_value                   NUMERIC(20,8),
    offer_price                 NUMERIC(20,8),
    price_range                 JSONB,
    green_shoe_option           BOOLEAN        DEFAULT FALSE,
    green_shoe_shares           BIGINT,
    lock_up_period_days         INT,
    prospectus_submitted_date   DATE,
    prospectus_approval_date    DATE,
    sec_approval_ref            VARCHAR(80),
    nse_approval_ref            VARCHAR(80),
    application_open_date       DATE,
    application_close_date      DATE,
    basis_of_allotment          TEXT,
    refund_start_date           DATE,
    listing_date                DATE,
    opening_price               NUMERIC(20,8),
    closing_price_day1          NUMERIC(20,8),
    price_performance_30_days   NUMERIC(8,4),
    retail_allocation_pct       NUMERIC(5,2),
    institutional_allocation_pct NUMERIC(5,2),
    total_applications          BIGINT,
    total_amount_received       NUMERIC(20,4),
    status                      VARCHAR(15)    NOT NULL DEFAULT 'PLANNING' CHECK (status IN ('PLANNING','SEC_REVIEW','APPROVED','OPEN','CLOSED','ALLOTTED','LISTED','WITHDRAWN')),
    created_by                  VARCHAR(100),
    updated_by                  VARCHAR(100),
    created_at                  TIMESTAMP      NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMP      NOT NULL DEFAULT now(),
    version                     BIGINT         DEFAULT 0
);

-- 4. Private Placement
CREATE TABLE IF NOT EXISTS private_placement (
    id                          BIGSERIAL PRIMARY KEY,
    placement_code              VARCHAR(30)    NOT NULL UNIQUE,
    deal_id                     BIGINT         REFERENCES capital_market_deal(id),
    placement_type              VARCHAR(30)    NOT NULL CHECK (placement_type IN ('EQUITY_PRIVATE_PLACEMENT','DEBT_PRIVATE_PLACEMENT','CONVERTIBLE_NOTE','MEZZANINE','PREFERENCE_SHARES','VENTURE_ROUND','PRE_IPO')),
    issuer_name                 VARCHAR(200)   NOT NULL,
    issuer_customer_id          BIGINT,
    currency                    VARCHAR(3)     NOT NULL DEFAULT 'NGN',
    target_amount               NUMERIC(20,4)  NOT NULL,
    raised_amount               NUMERIC(20,4)  DEFAULT 0,
    instrument_description      TEXT,
    coupon_rate                 NUMERIC(8,4),
    maturity_date               DATE,
    conversion_terms            JSONB,
    minimum_subscription        NUMERIC(20,4),
    max_investors               INT,
    current_investors           INT            DEFAULT 0,
    eligibility_type            VARCHAR(25)    NOT NULL CHECK (eligibility_type IN ('QUALIFIED_INSTITUTIONAL','ACCREDITED','HNI','SOPHISTICATED','STAFF')),
    offering_memorandum_ref     VARCHAR(200),
    sec_exemption_ref           VARCHAR(80),
    closing_date                DATE,
    funds_received_date         DATE,
    our_role                    VARCHAR(20)    NOT NULL CHECK (our_role IN ('PLACEMENT_AGENT','ARRANGER','FINANCIAL_ADVISER','INVESTOR')),
    our_fee_type                VARCHAR(15)    CHECK (our_fee_type IN ('FLAT','PERCENTAGE','SUCCESS_BASED')),
    our_fee_amount              NUMERIC(15,4),
    status                      VARCHAR(15)    NOT NULL DEFAULT 'STRUCTURING' CHECK (status IN ('STRUCTURING','MARKETING','SUBSCRIPTION','CLOSED','FUNDED','CANCELLED')),
    created_by                  VARCHAR(100),
    updated_by                  VARCHAR(100),
    created_at                  TIMESTAMP      NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMP      NOT NULL DEFAULT now(),
    version                     BIGINT         DEFAULT 0
);

-- 5. Placement Investor
CREATE TABLE IF NOT EXISTS placement_investor (
    id                          BIGSERIAL PRIMARY KEY,
    placement_id                BIGINT         NOT NULL REFERENCES private_placement(id),
    investor_name               VARCHAR(200)   NOT NULL,
    investor_type               VARCHAR(20)    NOT NULL,
    commitment_amount           NUMERIC(20,4)  NOT NULL,
    paid_amount                 NUMERIC(20,4)  DEFAULT 0,
    units_allocated             NUMERIC(20,6),
    subscription_date           DATE,
    kyc_verified                BOOLEAN        DEFAULT FALSE,
    accreditation_verified      BOOLEAN        DEFAULT FALSE,
    status                      VARCHAR(15)    NOT NULL DEFAULT 'COMMITTED' CHECK (status IN ('INVITED','COMMITTED','FUNDED','WITHDRAWN')),
    created_by                  VARCHAR(100),
    updated_by                  VARCHAR(100),
    created_at                  TIMESTAMP      NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMP      NOT NULL DEFAULT now(),
    version                     BIGINT         DEFAULT 0
);

-- 6. Client Risk Profile (MiFID II / SEC-style suitability profiling)
CREATE TABLE IF NOT EXISTS client_risk_profile (
    id                          BIGSERIAL PRIMARY KEY,
    profile_code                VARCHAR(30)    NOT NULL UNIQUE,
    customer_id                 BIGINT         NOT NULL,
    profile_date                DATE           NOT NULL,
    investment_objective        VARCHAR(20)    NOT NULL CHECK (investment_objective IN ('CAPITAL_PRESERVATION','INCOME','BALANCED','GROWTH','AGGRESSIVE_GROWTH','SPECULATION')),
    risk_tolerance              VARCHAR(15)    NOT NULL CHECK (risk_tolerance IN ('CONSERVATIVE','MODERATE','BALANCED','AGGRESSIVE','VERY_AGGRESSIVE')),
    investment_horizon          VARCHAR(15)    NOT NULL CHECK (investment_horizon IN ('SHORT_TERM','MEDIUM_TERM','LONG_TERM','VERY_LONG_TERM')),
    annual_income               NUMERIC(20,4),
    net_worth                   NUMERIC(20,4),
    liquid_net_worth            NUMERIC(20,4),
    investment_experience       VARCHAR(15)    CHECK (investment_experience IN ('NONE','LIMITED','MODERATE','EXTENSIVE','PROFESSIONAL')),
    instrument_experience       JSONB,
    knowledge_assessment_score  NUMERIC(5,2),
    concentration_limits        JSONB,
    max_single_investment_pct   NUMERIC(5,2),
    derivatives_approved        BOOLEAN        DEFAULT FALSE,
    leverage_approved           BOOLEAN        DEFAULT FALSE,
    max_leverage_ratio          NUMERIC(5,2),
    assessed_by                 VARCHAR(200),
    next_review_date            DATE,
    regulatory_basis            VARCHAR(20)    CHECK (regulatory_basis IN ('MIFID_II','SEC_REGULATION','CBN_GUIDELINE','INTERNAL_POLICY')),
    status                      VARCHAR(15)    NOT NULL DEFAULT 'ACTIVE' CHECK (status IN ('DRAFT','ACTIVE','EXPIRED','UNDER_REVIEW')),
    created_by                  VARCHAR(100),
    updated_by                  VARCHAR(100),
    created_at                  TIMESTAMP      NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMP      NOT NULL DEFAULT now(),
    version                     BIGINT         DEFAULT 0
);

CREATE INDEX idx_criskprf_customer ON client_risk_profile(customer_id, status);

-- 7. Suitability Check (standalone, immutable assessment record)
CREATE TABLE IF NOT EXISTS suitability_check (
    id                          BIGSERIAL PRIMARY KEY,
    check_ref                   VARCHAR(30)    NOT NULL UNIQUE,
    customer_id                 BIGINT         NOT NULL,
    profile_id                  BIGINT         NOT NULL REFERENCES client_risk_profile(id),
    check_type                  VARCHAR(20)    NOT NULL CHECK (check_type IN ('PRE_TRADE','PERIODIC_REVIEW','PRODUCT_CHANGE','PORTFOLIO_REBALANCE','ADVISORY')),
    instrument_type             VARCHAR(20)    NOT NULL,
    instrument_code             VARCHAR(30),
    instrument_risk_rating      VARCHAR(15)    CHECK (instrument_risk_rating IN ('LOW_RISK','MEDIUM_RISK','HIGH_RISK','VERY_HIGH_RISK','SPECULATIVE')),
    proposed_amount             NUMERIC(20,4),
    proposed_pct_of_portfolio   NUMERIC(5,2),
    proposed_pct_of_net_worth   NUMERIC(5,2),
    risk_tolerance_match        BOOLEAN,
    experience_match            BOOLEAN,
    concentration_check         BOOLEAN,
    liquidity_check             BOOLEAN,
    knowledge_check             BOOLEAN,
    leverage_check              BOOLEAN,
    overall_result              VARCHAR(20)    NOT NULL CHECK (overall_result IN ('SUITABLE','UNSUITABLE','SUITABLE_WITH_WARNING')),
    warning_messages            JSONB,
    rejection_reasons           JSONB,
    override_applied            BOOLEAN        DEFAULT FALSE,
    override_justification      TEXT,
    override_approved_by        VARCHAR(80),
    regulatory_disclosure       TEXT,
    client_acknowledged         BOOLEAN        DEFAULT FALSE,
    client_acknowledged_at      TIMESTAMP,
    checked_at                  TIMESTAMP      NOT NULL DEFAULT now(),
    created_by                  VARCHAR(100),
    created_at                  TIMESTAMP      NOT NULL DEFAULT now()
);
