-- V72: ACH item-level tracking and bulk payment item rows
-- Supports inbound item posting/return and CSV-parsed bulk payment rows

-- Bulk payment parent batch records
CREATE TABLE IF NOT EXISTS cbs.bulk_payment_batch (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_ref            VARCHAR(40)   NOT NULL UNIQUE,
    batch_name           VARCHAR(200),
    uploaded_by          VARCHAR(120),
    upload_file_name     VARCHAR(255),
    total_records        INTEGER       NOT NULL DEFAULT 0,
    valid_records        INTEGER       NOT NULL DEFAULT 0,
    invalid_records      INTEGER       NOT NULL DEFAULT 0,
    processed_records    INTEGER       NOT NULL DEFAULT 0,
    failed_records       INTEGER       NOT NULL DEFAULT 0,
    total_amount         NUMERIC(18,2) NOT NULL DEFAULT 0,
    debit_account_number VARCHAR(34),
    batch_type           VARCHAR(30)   NOT NULL DEFAULT 'PAYMENT',
    status               VARCHAR(30)   NOT NULL DEFAULT 'UPLOADED',
    created_by           VARCHAR(120),
    approved_by          VARCHAR(120),
    approved_at          TIMESTAMPTZ,
    rejected_by          VARCHAR(120),
    rejected_at          TIMESTAMPTZ,
    rejection_reason     VARCHAR(500),
    created_at           TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ   NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_bulk_batch_ref ON cbs.bulk_payment_batch(batch_ref);
CREATE INDEX IF NOT EXISTS idx_bulk_batch_status ON cbs.bulk_payment_batch(status);

-- ACH individual items within a batch
CREATE TABLE IF NOT EXISTS cbs.ach_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id        BIGINT       NOT NULL REFERENCES cbs.ach_batch(id),
    sequence_number INTEGER,
    account_number  VARCHAR(34),
    routing_number  VARCHAR(20),
    account_name    VARCHAR(200),
    transaction_code VARCHAR(10),
    amount          NUMERIC(18,2),
    addenda         VARCHAR(300),
    status          VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    return_code     VARCHAR(10),
    return_reason   VARCHAR(300),
    posted_at       TIMESTAMPTZ,
    returned_at     TIMESTAMPTZ,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ach_item_batch ON cbs.ach_item(batch_id);
CREATE INDEX IF NOT EXISTS idx_ach_item_status ON cbs.ach_item(status);

-- Bulk payment individual rows parsed from uploaded CSV
CREATE TABLE IF NOT EXISTS cbs.bulk_payment_item (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id        BIGINT       NOT NULL REFERENCES cbs.bulk_payment_batch(id),
    row_number      INTEGER      NOT NULL,
    beneficiary_name VARCHAR(200),
    account_number  VARCHAR(34),
    bank_code       VARCHAR(20),
    amount          NUMERIC(18,2),
    narration       VARCHAR(300),
    status          VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    error_message   VARCHAR(500),
    transaction_ref VARCHAR(40),
    execution_status VARCHAR(20),
    failure_reason  VARCHAR(300),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_bulk_item_batch ON cbs.bulk_payment_item(batch_id);
CREATE INDEX IF NOT EXISTS idx_bulk_item_status ON cbs.bulk_payment_item(status);
