package com.cbs.shariahcompliance.entity;

public enum AlertType {
    HARAM_ACTIVITY, STRUCTURAL_VIOLATION, PRODUCT_NON_COMPLIANCE, RATE_VIOLATION, GHARAR, RIBA_INDICATOR, OWNERSHIP_VIOLATION, POOL_VIOLATION, OTHER
}
