package com.cbs.shariahcompliance.entity;

public enum AuditEntityType {
    MURABAHA_CONTRACT, IJARAH_CONTRACT, MUDARABAH_DEPOSIT, INVESTMENT_POOL, PROFIT_DISTRIBUTION, FEE_CHARGE, PAYMENT, PRODUCT_TEMPLATE, OTHER
}
