package com.cbs.shariahcompliance.entity;

public enum NonComplianceType {
    HARAM_ACTIVITY, STRUCTURAL_VIOLATION, RIBA_ELEMENT, GHARAR, OWNERSHIP_VIOLATION, PRODUCT_NON_COMPLIANT, INVESTMENT_NON_COMPLIANT, RETROACTIVE_RULING, OTHER
}
