package com.cbs.quotemanagement.entity;

import com.cbs.common.audit.AuditableEntity;
import jakarta.persistence.*;
import lombok.*;
import lombok.experimental.SuperBuilder;

import java.math.BigDecimal;
import java.time.Instant;

@Entity
@Table(name = "price_quote", schema = "cbs")
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @SuperBuilder
public class PriceQuote extends AuditableEntity {

    @Id @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "quote_ref", nullable = false, unique = true, length = 30)
    private String quoteRef;

    @Column(name = "desk_id")
    private Long deskId;

    @Column(name = "dealer_id", nullable = false, length = 80)
    private String dealerId;

    @Column(name = "quote_type", nullable = false, length = 15)
    private String quoteType;

    @Column(name = "instrument_type", nullable = false, length = 20)
    private String instrumentType;

    @Column(name = "instrument_code", length = 30)
    private String instrumentCode;

    @Column(name = "currency_pair", length = 7)
    private String currencyPair;

    @Column(name = "tenor", length = 10)
    private String tenor;

    @Column(name = "bid_price", nullable = false, precision = 20, scale = 8)
    private BigDecimal bidPrice;

    @Column(name = "ask_price", nullable = false, precision = 20, scale = 8)
    private BigDecimal askPrice;

    @Column(name = "mid_price", precision = 20, scale = 8)
    private BigDecimal midPrice;

    @Column(name = "spread_bps", precision = 8, scale = 2)
    private BigDecimal spreadBps;

    @Column(name = "notional_amount", precision = 20, scale = 4)
    private BigDecimal notionalAmount;

    @Column(name = "currency", nullable = false, length = 3)
    private String currency;

    @Column(name = "counterparty_code", length = 30)
    private String counterpartyCode;

    @Column(name = "counterparty_name", length = 200)
    private String counterpartyName;

    @Column(name = "valid_from_time", nullable = false)
    private Instant validFromTime;

    @Column(name = "valid_until_time")
    private Instant validUntilTime;

    @Column(name = "is_auto_generated")
    private Boolean isAutoGenerated;

    @Column(name = "pricing_model", length = 30)
    private String pricingModel;

    @Column(name = "market_data_ref", length = 30)
    private String marketDataRef;

    @Column(name = "status", nullable = false, length = 15)
    private String status;

    @Column(name = "traded_ref", length = 30)
    private String tradedRef;
}
