package com.cbs.document.entity;

public enum DocumentType {
    ID_DOCUMENT, ADDRESS_PROOF, INCOME_PROOF, BANK_STATEMENT,
    TAX_CERTIFICATE, REGISTRATION_CERT, FINANCIAL_STATEMENT,
    COLLATERAL_DOC, LOAN_AGREEMENT, GUARANTEE_LETTER,
    BOARD_RESOLUTION, MANDATE_FORM, OTHER
}
