export const queryKeys = {
  customers: {
    all: ['customers'] as const,
    list: (filters?: Record<string, unknown>) => ['customers', 'list', filters] as const,
    detail: (id: number) => ['customers', 'detail', id] as const,
    accounts: (id: number) => ['customers', id, 'accounts'] as const,
    search: (query: string) => ['customers', 'search', query] as const,
  },
  accounts: {
    all: ['accounts'] as const,
    list: (filters?: Record<string, unknown>) => ['accounts', 'list', filters] as const,
    detail: (id: number) => ['accounts', 'detail', id] as const,
    transactions: (id: number, params?: Record<string, unknown>) => ['accounts', id, 'transactions', params] as const,
    balance: (id: number) => ['accounts', id, 'balance'] as const,
  },
  loans: {
    all: ['loans'] as const,
    list: (filters?: Record<string, unknown>) => ['loans', 'list', filters] as const,
    detail: (id: number) => ['loans', 'detail', id] as const,
    schedule: (id: number) => ['loans', id, 'schedule'] as const,
    applications: (filters?: Record<string, unknown>) => ['loans', 'applications', filters] as const,
    products: (filters?: Record<string, unknown>) => ['loans', 'products', filters] as const,
    schedulePreview: (payload?: Record<string, unknown>) => ['loans', 'schedule-preview', payload] as const,
  },
  payments: {
    all: ['payments'] as const,
    list: (filters?: Record<string, unknown>) => ['payments', 'list', filters] as const,
    detail: (id: number) => ['payments', 'detail', id] as const,
    accounts: ['payments', 'accounts'] as const,
    beneficiaries: ['payments', 'beneficiaries'] as const,
    banks: ['payments', 'banks'] as const,
    recent: ['payments', 'recent'] as const,
    feePreview: (amount: number, type: string) => ['payments', 'fee-preview', amount, type] as const,
    bulkBatch: (id: number) => ['bulk-payment', id] as const,
    bulkStatus: (id: number) => ['bulk-payment', 'status', id] as const,
    standingOrders: (filters?: Record<string, unknown>) => ['standing-orders', filters] as const,
    standingOrderDetail: (id: number) => ['standing-orders', id] as const,
    standingOrderExecutions: (id: number) => ['standing-orders', id, 'executions'] as const,
    directDebits: (filters?: Record<string, unknown>) => ['direct-debits', filters] as const,
    billCategories: ['bill-categories'] as const,
    billers: (category: string) => ['billers', category] as const,
    billFavorites: ['bill-favorites'] as const,
    fxRate: (from: string, to: string) => ['fx-rate', from, to] as const,
    intlCharges: (amount: number, currency: string) => ['intl-charges', amount, currency] as const,
  },
  cards: {
    all: ['cards'] as const,
    list: (filters?: Record<string, unknown>) => ['cards', 'list', filters] as const,
    detail: (id: number) => ['cards', 'detail', id] as const,
    transactions: (filters?: Record<string, unknown>) => ['cards', 'transactions', filters] as const,
  },
  treasury: {
    deals: (filters?: Record<string, unknown>) => ['treasury', 'deals', filters] as const,
    positions: (type?: string) => ['treasury', 'positions', type] as const,
  },
  risk: {
    amlAlerts: (filters?: Record<string, unknown>) => ['risk', 'aml', filters] as const,
    fraudAlerts: (filters?: Record<string, unknown>) => ['risk', 'fraud', filters] as const,
    varStats: ['risk', 'var-stats'] as const,
    varTrend: ['risk', 'var-trend'] as const,
    varByFactor: ['risk', 'var-by-factor'] as const,
    stressTests: ['risk', 'stress-tests'] as const,
    sensitivities: ['risk', 'sensitivities'] as const,
    backtest: ['risk', 'backtest'] as const,
    liquidityRatios: ['risk', 'liq-ratios'] as const,
    cashflowLadder: ['risk', 'cashflow'] as const,
    hqla: ['risk', 'hqla'] as const,
    liquidityStress: ['risk', 'liq-stress'] as const,
    opriskStats: ['oprisk', 'stats'] as const,
    lossEvents: (filters?: Record<string, unknown>) => ['oprisk', 'losses', filters] as const,
    lossByCategory: ['oprisk', 'loss-by-cat'] as const,
    kris: ['oprisk', 'kris'] as const,
    rcsa: ['oprisk', 'rcsa'] as const,
    incidents: (filters?: Record<string, unknown>) => ['oprisk', 'incidents', filters] as const,
  },
  compliance: {
    stats: ['compliance', 'stats'] as const,
    assessments: ['compliance', 'assessments'] as const,
    gaps: (filters?: Record<string, unknown>) => ['compliance', 'gaps', filters] as const,
    policies: ['compliance', 'policies'] as const,
    auditFindings: (filters?: Record<string, unknown>) => ['compliance', 'findings', filters] as const,
    returnStats: ['reg-returns', 'stats'] as const,
    returnCalendar: (month: string) => ['reg-returns', 'calendar', month] as const,
    returns: (filters?: Record<string, unknown>) => ['reg-returns', 'all', filters] as const,
    returnDetail: (id: number) => ['reg-returns', id] as const,
    returnValidations: (id: number) => ['reg-returns', id, 'validations'] as const,
    auditSearch: (params: Record<string, unknown>) => ['audit', 'search', params] as const,
    auditSummary: (params: Record<string, unknown>) => ['audit', 'summary', params] as const,
    auditHeatmap: (userId: string) => ['audit', 'heatmap', userId] as const,
  },
  dashboard: {
    stats: ['dashboard', 'stats'] as const,
    recentTransactions: ['dashboard', 'recent-transactions'] as const,
    charts: (period: string) => ['dashboard', 'charts', period] as const,
  },
  gl: {
    journals: (filters?: Record<string, unknown>) => ['gl', 'journals', filters] as const,
    balances: (date?: string) => ['gl', 'balances', date] as const,
  },
  agreements: {
    all: ['agreements'] as const,
    list: (filters?: Record<string, unknown>) => ['agreements', 'list', filters] as const,
    detail: (id: number) => ['agreements', 'detail', id] as const,
    byCustomer: (customerId: number) => ['agreements', 'customer', customerId] as const,
    templates: ['agreements', 'templates'] as const,
  },
  communications: {
    all: ['communications'] as const,
    list: (filters?: Record<string, unknown>) => ['communications', 'list', filters] as const,
    byCustomer: (customerId: number) => ['communications', 'customer', customerId] as const,
    templates: ['communication-templates'] as const,
    preferences: (customerId: number) => ['communications', 'preferences', customerId] as const,
    stats: ['communications', 'stats'] as const,
  },
  cases: {
    all: ['cases'] as const,
    list: (filters?: Record<string, unknown>) => ['cases', 'list', filters] as const,
    detail: (id: number) => ['cases', 'detail', id] as const,
    stats: ['cases', 'stats'] as const,
    my: ['cases', 'my'] as const,
    unassigned: ['cases', 'unassigned'] as const,
  },
} as const;
